---
php_ini:
    'date.timezone': "Europe/Berlin"
    'max_execution_time': 300
    'request_terminate_timeout': 300
    'upload_max_filesize': 512M
    'post_max_size': 512M

    'xdebug.remote_host': "192.168.222.1"
    'xdebug.remote_autostart': 1
    'xdebug.max_nesting_level': 1200
    'xdebug.remote_addr_header': "HTTP_XDEBUG_HOST"
